### ISSUE TITLE
Request for a rom upload

### ISSUE THREAD

**Issue by HtmlBosss** [Board-Folk/CPC464-2MINI#1]
Hey, can you upload a ROM for 39SF040?

**Comment by grandoldian** [comment]
Not sure I'm allowed for copyright reasons really, but if you get the basics of this:

copy /b cpc464.rom+40009-r2.rom+40025.rom+noel_1_3.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom+blank32.rom build1.rom

You should be on the right lines.
Atb, didn't think there'd be any interest. :-)
Ian.
